### ISSUE TITLE
Error while generating Secret Key

### ISSUE THREAD

**Issue by Pierpaolo1992** [mozilla/fxa-webrtc-idp#1]
When i launch /bin/gen_keys.js, this is what appairs:

```
root@4cdc2d5c1f58:/fxa-webrtc-idp# ./bin/gen_keys.js 
Generating keypair
Secret Key saved: /fxa-webrtc-idp/config/secret-key.json
undefined:1



SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /fxa-webrtc-idp/bin/gen_keys.js:49:18
    at ChildProcess.exithandler (child_process.js:218:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:192:7)
    at maybeClose (internal/child_process.js:890:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

```

With `vim`, i see nothing inside secret-key.json; then because of this error, script cannot create public key.

**Comment by rfk** [comment]
I'm going to archive this repo, closing out old issues.
